services:
  rt-core-npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: rt-core-npm
    restart: unless-stopped

    ports:
      - "80:80"
      - "81:81"
      - "443:443"

    volumes:
      - rt-vol-npm-data:/data
      - rt-vol-npm-letsencrypt:/etc/letsencrypt

    networks:
      - rt-network

volumes:
  rt-vol-npm-data:
    name: rt-vol-npm-data

  rt-vol-npm-letsencrypt:
    name: rt-vol-npm-letsencrypt

networks:
  rt-network:
    external: true